#!/usr/bin/php
<?php
/**
 * Set up LightFrame
 * 
 * Copy files to appropriate places, make softlinks for index.php, setup.php and 
 * .htaccess. Determine whether mod_rewrite is supported. Determine SQL type
 * and ask for host/user/pass.
 * 
 * [ the following are implemented ]
 * startproject[ <path>] -- where to place user's files
 * scanserver -- check for server's support of features
 *
 * [ the following are proposed ]
 * startapp[ <path>] -- 
 * show sql -- show the SQL generated by the models
 * show sqldiff -- show the SQL required to modify the current database to match those defined in models
 * version --
 * help --
 * 
 */

define('DISLPAY_HELP', true);
define('SETUP_VERSION', '0');
define('ANSI', chr(27).'[9');
define('GREY', ANSI.'0m');
define('RED', ANSI.'1m');
define('GREEN', ANSI.'2m');
define('YELLOW', ANSI.'3m');
define('BLUE', ANSI.'4m');
define('MAGENTA', ANSI.'5m');
define('CYAN', ANSI.'6m');
define('WHITE', ANSI.'7m');
define('OFF', chr(27).'[0m');

if (!defined("STDIN")) {
	die("You must run this script in the command line");
}

// show the command line help per default
if ($_SERVER['argc'] < 2) {
	setup_help(false);
	die();
}

$option = "setup_".strtolower($_SERVER['argv'][1]);
$value = $_SERVER['argv'][2];

if (function_exists($option)) {
	$option($value);
}
else {
	die("Unknown command\n\n");
}

function setup_help($arg) {
	if (!$arg) {
		echo
		"To get more info about a particular command, use 'help <command>' as an argument.\n".
		"\n".
		"startproject\n".
		"scanserver\n".
		"\n";
	}
	elseif (function_exists('setup_'.$arg)) {
		$function = 'setup_'.$arg;
		echo $function(DISPLAY_HELP);
	}
	else {
		die("No such command\n\n");
	}
}


function setup_startproject($arg) {
	if ($arg === DISPLAY_HELP) {
		echo 
		WHITE."startproject: ".OFF."copy template files needed for a new LightFrame project\n".
		"usage: ".WHITE."startproject".OFF." [PATH]\n".
		"\n".
		wordwrap("if PATH is provided, the files will be copied to that path. Otherwise they are copied to the current working path\n").
		"\n";
		die();
	}
	
	if (!$arg) {
		$path = getcwd();
	}
	else {
		$path = $arg;
	}
	
	$templatepath = dirname(__FILE__).'/projectfiles';
	if (!is_dir($templatepath)) {
		die("'$templatepath' is not a directory\n");
	}
	
	chdir($templatepath);
	_startproject_install(_startproject_findfilesfrom('./'), $path);
	
	echo "\nnew project created!\n\n";
}

function setup_scanserver($arg) {
	if ($arg === DISPLAY_HELP) {
		echo "meh\n\n";
		die();
	}
	
	// I'm checking for everything atm. Take out everything that's not supported!
	$features = array(
		'SQL' => array(
			'MySQL          (mysql) ' => function_exists('mysql_connect'),
			'MySQL Improved (mysqli)' => function_exists('mysqli_connect'),
			'MySQL Improved ()      ' => class_exists('mysqli'),
			'PostgreSQL     (pgsql) ' => function_exists('pg_connect'),
			'SQLite         (sqlite)' => function_exists('sqlite_open'),
			'SQLite         ()      ' => class_exists('SQLiteDatabase'),
			'PDO            ()      ' => class_exists('PDO')
		),
		'Compression' => array(
			'ZIP   ()' => function_exists('zip_open'),
			'ZIP   ()' => class_exists('ZipArchive'),
			'GZip  ()' => function_exists('gzopen'),
			'BZip2 ()' => function_exists('bzopen'),
			'RAR   ()' => function_exists('rar_open')
		),
		'Image Manipulation' => array (
			'ImageMagick ()' => class_exists('Imagick'),
			'GDLib       ()' => function_exists('imagecreate')
		)
	);
	
	foreach ($features as $group => $featureset) {
		echo "$group:\n";
		foreach ($featureset as $setting => $status) {
			echo "  $setting: ".($status?"yes":"no")."\n";
		}
		echo "\n";
	}
	
	if (!in_array(true, $features['SQL'])) {
		echo "The server doesn't have a supported database engine. LightFrame functionality will be very limited.\n";
	}
	
	echo "\n";
}


// Auxiliary functions




function _startproject_findfilesfrom($path) {
	if (!is_readable(getcwd().'/'.$path)) {
		die("directory is not readable: '".getcwd()."/$path'\n");
	}
	
	foreach (glob($path.'*') as $line) {
		if (is_dir(getcwd().'/'.$line)) {
			$files[] = _findfilesfrom($line.'/');
		}
		else {
			if (!is_readable(getcwd().'/'.$line)) {
				die("can't read file '".getcwd()."/$line'\n");
			}
			else {
				$files[] = $line;
			}
		}
	}
	return $files;
}


function _startproject_install($filelist, $destination) {
	if (!is_dir($destination) || !is_writable($destination)) {
		die("can't write to directory '$destination'\n");
	}
	
	if (glob($destination.'/*')) {
		die("'$destination' is not an empty directory. Can't start a new project!\n");
	}
	
	foreach($filelist as $file) {
		if (is_array($file)) {
			mkdir($destination.'/'.substr(dirname($file[0]),2));
			_install($file, $destination.'/'.substr(dirname($file[0]),2));
		}
		else {
			echo substr($file,2)." > $destination\n";
			copy($file, $destination.'/'.basename($file));
		}
	}
}
?>